#!/usr/bin/env python

import sys
import subprocess
import sshcachefs

class CacheFsManager(object):

    def __init__(self, argv):
        assert(len(argv) < 3)
        if len(argv) == 2:
            self.config = sys.argv[1]
        else:
            self.config = 'config'

    def run(self):
        subprocess.call(['python', 'sshcachefs.py', self.config])
               
    def stop(self):
        pass

def usage():
    print("juda [config_module], ex. juda config")
    sys.exit(1)

def main():
    cacheFsManager = CacheFsManager(sys.argv) 
    cacheFsManager.run()

if __name__ == '__main__':
    main()
