#!/usr/bin/env python

import sys
print(sys.argv)

if __name__ == '__main__':
    import_config = 'config'
    if len(sys.argv) == 2:
        import_config = sys.argv[1]
    exec('import %s as config' % import_config)

print `config`
